version: 2
jobs:
  build:
    docker:
      - image: clojure:lein
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: test
          command: |
            lein test